### ISSUE TITLE
error when reading certain jpg files as input

### ISSUE THREAD

**Issue by selul** [axe312ger/sqip#93]
Hey, 

I've started to use recently the sqip library, the alpha version and is working great. 

Lately, for some images, I'm getting this error 
```
TypeError: Corrupt JPG, exceeded buffer limits
at validateBuffer (/node_modules/image-size/lib/types/jpg.js:98:11)
at Object.calculate (/node_modules/image-size/lib/types/jpg.js:122:5)
at lookup (/node_modules/image-size/lib/index.js:26:35)
at module.exports (/node_modules/image-size/lib/index.js:122:12)
at processImage (/node_modules/sqip/dist/sqip.js:93:48)
at sqip (/node_modules/sqip/dist/sqip.js:199:26)
```

which seems to be caused by the `image-size` library, I've found more details about this topic here https://github.com/image-size/image-size/issues/37 

It seems that by switching to https://github.com/nodeca/probe-image-size the issue is no longer present. 

Thanks a lot for your work!

**Comment by axe312ger** [comment]
Thanks for testing and the report :)

I'll have a look at prope-image-size and also consider just using sharp to get the dimensions as sharp is already in the project as dependency
